-- MySQL Script generated by MySQL Workbench
-- Mon Nov  8 14:44:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema online_store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema online_store
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `online_store` DEFAULT CHARACTER SET utf8 ;
USE `online_store` ;

-- -----------------------------------------------------
-- Table `online_store`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store`.`categories` ;

CREATE TABLE IF NOT EXISTS `online_store`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `picture` MEDIUMBLOB NOT NULL,
  `subcategory_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_category_category_idx` (`subcategory_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_category`
    FOREIGN KEY (`subcategory_id`)
    REFERENCES `online_store`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_store`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store`.`products` ;

CREATE TABLE IF NOT EXISTS `online_store`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `picture` MEDIUMBLOB NOT NULL,
  `create_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `amount` INT UNSIGNED ZEROFILL NOT NULL,
  `price` DECIMAL(9,2) UNSIGNED NOT NULL,
  `discount` INT UNSIGNED ZEROFILL NOT NULL,
  `active` BIT NOT NULL DEFAULT 1,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `online_store`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_store`.`special_options`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store`.`special_options` ;

CREATE TABLE IF NOT EXISTS `online_store`.`special_options` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(45) NULL,
  `value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC) VISIBLE,
  UNIQUE INDEX `value_UNIQUE` (`value` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_store`.`banners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store`.`banners` ;

CREATE TABLE IF NOT EXISTS `online_store`.`banners` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `picture` MEDIUMBLOB NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_banner_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_banner_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `online_store`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_store`.`surnames`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store`.`users` ;

CREATE TABLE IF NOT EXISTS `online_store`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `create_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `blocked` BIT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `telephone_UNIQUE` (`phone` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_store`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store`.`addresses` ;

CREATE TABLE IF NOT EXISTS `online_store`.`addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `region` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `courier` BIT NOT NULL DEFAULT 0,
  `street` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_address_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `online_store`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_store`.`receipts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store`.`receipts` ;

CREATE TABLE IF NOT EXISTS `online_store`.`receipts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` ENUM('ordered', 'paid', 'canceled') NOT NULL,
  `create_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_purchase_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_receipt_address1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_purchase_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `online_store`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receipt_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `online_store`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_store`.`promo_codes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store`.`promo_codes` ;

CREATE TABLE IF NOT EXISTS `online_store`.`promo_codes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `discount` TINYINT UNSIGNED NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_promo_code_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_promo_code_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `online_store`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_store`.`categories_has_special_options`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store`.`categories_has_special_options` ;

CREATE TABLE IF NOT EXISTS `online_store`.`categories_has_special_options` (
  `category_id` INT NOT NULL,
  `special_options_id` INT NOT NULL,
  PRIMARY KEY (`category_id`, `special_options_id`),
  INDEX `fk_category_has_special_options_special_options1_idx` (`special_options_id` ASC) VISIBLE,
  INDEX `fk_category_has_special_options_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_has_special_options_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `online_store`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_has_special_options_special_options1`
    FOREIGN KEY (`special_options_id`)
    REFERENCES `online_store`.`special_options` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_store`.`products_has_receipts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store`.`products_has_receipts` ;

CREATE TABLE IF NOT EXISTS `online_store`.`products_has_receipts` (
  `products_id` INT NOT NULL,
  `receipts_id` INT NOT NULL,
  PRIMARY KEY (`products_id`, `receipts_id`),
  INDEX `fk_products_has_receipts_receipts1_idx` (`receipts_id` ASC) VISIBLE,
  INDEX `fk_products_has_receipts_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_has_receipts_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `online_store`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_receipts_receipts1`
    FOREIGN KEY (`receipts_id`)
    REFERENCES `online_store`.`receipts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_store`.`product_translations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `online_store`.`product_translations` ;

CREATE TABLE IF NOT EXISTS `online_store`.`product_translations` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`, `product_id`),
  INDEX `fk_product_translations_products1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_translations_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `online_store`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
